cc_library(
    name="common",
    srcs=[
        "common/bitset.cpp",
        "common/intset.cpp",
        "common/hypergraph.cpp"
    ],
    hdrs=[
        "common/bitset.h",
        "common/intset.h",
        "common/hypergraph.h",
        "common/concurrent_drop_head_queue.h"
    ],
    deps=[
        "@com_github_google_glog//:glog",
    ]
)

cc_binary(
    name="test_code",
    srcs=["test/test_code.cpp"],
    deps=[
        ":common",
        "@com_github_google_glog//:glog",
    ]
)

cc_test(
    name="intset_test",
    srcs=["test/intset_test.cpp"],
    deps=[
        ":common",
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name="hypergraph_test",
    srcs=["test/hypergraph_test.cpp"],
    deps=[
        ":common",
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name="concurrent_queue_test",
    srcs=["test/concurrent_drop_head_queue_test.cpp"],
    deps=[
        ":common",
        "@com_google_googletest//:gtest_main",
    ]
)